<?php /* Smarty version 2.6.10, created on 2017-03-19 16:34:03
         compiled from Main.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%8B^8BA^8BAC94BE%%Main.tpl.inc'] = '890637a70bf0aa25d14a36800bc6d250';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Main.tpl', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'GetAppInf','varName' => 'verName'), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/main1.css"), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap/css/bootstrap.css"), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/ext/include-ext.js"), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/ext/TabCloseMenu.js"), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.1.9.1.js"), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/MainNew.css"), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap/js/bootstrap.js"), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_8(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/ymPrompt.js"), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_9(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/skin/qq/ymPrompt.css"), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_10(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'GetAppInf','varName' => 'systemName'), $_smarty);
}


function _smarty_tplfunc_890637a70bf0aa25d14a36800bc6d250_11(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'GetAppInf','varName' => 'systemV'), $_smarty);
}



?>
