<?php /* Smarty version 2.6.10, created on 2018-04-09 16:33:01
         compiled from Main2Son/_jsCommon.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%D3^D3B^D3B46A51%%_jsCommon.tpl.inc'] = 'b44a4b995e4473daaba7bc373783f2c8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Main2Son/_jsCommon.tpl', 2, false),array('modifier', 'default', 'Main2Son/_jsCommon.tpl', 15, false),array('modifier', 'json_encode', 'Main2Son/_jsCommon.tpl', 17, false),)), $this); ?>
<?php
function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/Calendar/WdatePicker.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/common.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.1.9.1.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/layer/layer.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.validate.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap/js/bootstrap.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap/js/tooltip.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap/js/jeffCombobox.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_8(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap/js/TableHeader.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_9(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/select2/select2.js"), $_smarty);
}


function _smarty_tplfunc_b44a4b995e4473daaba7bc373783f2c8_10(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/select2/select2.css"), $_smarty);
}



?>
