<?php /* Smarty version 2.6.10, created on 2018-05-16 15:15:15
         compiled from Cangku/sonTpl.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%F5^F56^F56197E6%%sonTpl.tpl.inc'] = '612045b8706f5446e0075edcc9f30d23';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Cangku/sonTpl.tpl', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_612045b8706f5446e0075edcc9f30d23_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.json.js"), $_smarty);
}


function _smarty_tplfunc_612045b8706f5446e0075edcc9f30d23_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ajaxfileupload.js"), $_smarty);
}



?>
