<?php
$_sysMenu = array(
	array(
		'text'=>'采购管理',
		'expanded'=> false,
		'id'=>'1',
		'iconSpan'=>'glyphicon-log-in',
		'children'=>array(
			array(
				'text'=>'申购管理',
				'expanded'=> false,
				'id'=>'1-1',
				'iconCls'=>'x-tree-icon-hide',
				'children'=>array(
					array(
						'text'=>'申购单(Excel)导入',
						'expanded'=> false,
						'src'=>'?controller=Caigou_Shengou&action=Import',
						'leaf'=>true,
						'id'=>'1-1-4',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'申购单登记',
						'expanded'=> false,
						'src'=>'?controller=Caigou_Shengou&action=Add',
						'leaf'=>true,
						'id'=>'1-1-1',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'申购单查询',
						'expanded'=> false,
						'src'=>'?controller=Caigou_Shengou&action=Right',
						'leaf'=>true,
						'id'=>'1-1-2',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'采购报价审核',
						'expanded'=> false,
						'src'=>'?controller=Caigou_Shengou&action=ListShenhe',
						'leaf'=>true,
						'id'=>'1-1-3',
						'iconCls'=>'x-tree-icon-hide',
					),
				)
			),
			array(
				'text'=>'采购合同',
				'expanded'=> false,
				'id'=>'1-3',
				'iconCls'=>'x-tree-icon-hide',
				'children'=>array(
					array(
						'text'=>'合同登记',
						'expanded'=> false,
						'src'=>'?controller=Caigou_Order&action=Add',
						'leaf'=>true,
						'id'=>'1-3-2',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'合同查询',
						'expanded'=> false,
						'src'=>'?controller=Caigou_Order&action=Right',
						'leaf'=>true,
						'id'=>'1-3-3',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'合同审核',
						'expanded'=> false,
						'src'=>'?controller=Caigou_Order&action=ListShenhe',
						'leaf'=>true,
						'id'=>'1-3-4',
						'iconCls'=>'x-tree-icon-hide',
					),
				)
			)				
		)
    ),
	array(
		'text'=>'销售管理',
		'expanded'=> false,
		'id'=>'2',
		'iconSpan'=>'glyphicon glyphicon-tags',
		'children'=>array(
			array(
				'text'=>'配货单查询',
				'expanded'=> false,
				'src'=>'?controller=Trade_Peihuo&action=Right',
				'leaf'=>true,
				'id'=>'2-1',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'合同登记',
				'expanded'=> false,
				'src'=>'?controller=Trade_Order&action=Add',
				'leaf'=>true,
				'id'=>'2-2',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'合同查询',
				'expanded'=> false,
				'src'=>'?controller=Trade_Order&action=Right',
				'leaf'=>true,
				'id'=>'2-3',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'订单审核',
				'expanded'=> false,
				'src'=>'?controller=Trade_Order&action=Shenhe',
				'leaf'=>true,
				'id'=>'2-4',
				'iconCls'=>'x-tree-icon-hide',
			),
	    ),
	),
	array(
		'text'=>'仓库管理',
		'expanded'=> false,
		'id'=>'3',
		'iconSpan'=>'glyphicon-blackboard',
		'children'=>array(
			array(
				'text'=>__CANGKU_1,//变量定义在config/define.php中
				'expanded'=> false,
				'id'=>'3-1',
				'iconCls'=>'x-tree-icon-hide',
				'children'=>array(
					array(
						'text'=>'采购入库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_CaigouRk&action=Right',
						'leaf'=>true,
						'id'=>'3-1-2',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'加工入库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_JiagongRk&action=Add',
						'leaf'=>true,
						'id'=>'3-1-3',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'其他入库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_QtRk&action=Add',
						'leaf'=>true,
						'id'=>'3-1-5',
						'iconSpan'=>'x-tree-icon-hide',
					),
					// array(
					// 	'text'=>'入库审核',
					// 	'expanded'=> false,
					// 	'src'=>'?controller=Cangku_Xianhuo_Shrk&action=ShenheList',
					// 	'leaf'=>true,
					// 	'id'=>'3-1-13',
					// 	'iconSpan'=>'x-tree-icon-hide',
					// ),
					array(
						'text'=>'入库查询',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_QtRk&action=Right',
						'leaf'=>true,
						'id'=>'3-1-4',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'销售出库单',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_Plan&action=Right',
						'leaf'=>true,
						'id'=>'3-1-6',
						'iconSpan'=>'x-tree-icon-hide',
					),
					// array(
					// 	'text'=>'出库审核',
					// 	'expanded'=> false,
					// 	'src'=>'?controller=Cangku_Xianhuo_Shck&action=ShenheList',
					// 	'leaf'=>true,
					// 	'id'=>'3-1-14',
					// 	'iconSpan'=>'x-tree-icon-hide',
					// ),
					array(
						'text'=>'销售出库查询',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_Xsck&action=Right',
						'leaf'=>true,
						'id'=>'3-1-7',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'外协出库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_Jgck&action=Right',
						'leaf'=>true,
						'id'=>'3-1-8',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'调货出库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_Diaohuo&action=Right',
						'leaf'=>true,
						'id'=>'3-1-9',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'调整库位',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_Diaoku&action=Right',
						'leaf'=>true,
						'id'=>'3-1-17',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'退换货清单',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_BackPlan&action=BackPlan',
						'leaf'=>true,
						'id'=>'3-1-10',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'退换货查询',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_BackPlan&action=right',
						'leaf'=>true,
						'id'=>'3-1-11',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'现货库存报表',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_Report&action=ReportKucun',
						'leaf'=>true,
						'id'=>'3-1-12',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'库位库存报表',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Xianhuo_Report&action=KuquKucun',
						'leaf'=>true,
						'id'=>'3-1-15',
						'iconSpan'=>'x-tree-icon-hide',
					),
				)
			),
			array(
				'text'=>__CANGKU_2,
				'expanded'=> false,
				'id'=>'3-2',
				'iconCls'=>'x-tree-icon-hide',
				'children'=>array(
					array(
						'text'=>'采购入库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_CaigouRk&action=Right',
						'leaf'=>true,
						'id'=>'3-2-2',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'加工入库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_JiagongRk&action=Add',
						'leaf'=>true,
						'id'=>'3-2-3',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'其他入库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_QtRk&action=Add',
						'leaf'=>true,
						'id'=>'3-2-4',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'入库查询',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_QtRk&action=Right',
						'leaf'=>true,
						'id'=>'3-2-5',
						'iconSpan'=>'x-tree-icon-hide',
					),
					
					array(
						'text'=>'销售出库单',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_Plan&action=Right',
						'leaf'=>true,
						'id'=>'3-2-6',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'销售出库查询',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_Xsck&action=Right',
						'leaf'=>true,
						'id'=>'3-2-7',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'损耗出库单',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_Shck&action=Add',
						'leaf'=>true,
						'id'=>'3-2-61',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'损耗出库查询',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_Shck&action=Right',
						'leaf'=>true,
						'id'=>'3-2-62',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'外协出库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_Jgck&action=Right',
						'leaf'=>true,
						'id'=>'3-2-8',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'调货出库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_Diaohuo&action=Right',
						'leaf'=>true,
						'id'=>'3-2-9',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'退换货清单',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_BackPlan&action=BackPlan',
						'leaf'=>true,
						'id'=>'3-2-10',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'退换货查询',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_BackPlan&action=right',
						'leaf'=>true,
						'id'=>'3-2-11',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'		库存报表',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_Report&action=ReportKucun',
						'leaf'=>true,
						'id'=>'3-2-12',
						'iconSpan'=>'x-tree-icon-hide',
					),
				)
			),
			array(
				'text'=>__CANGKU_3,
				'expanded'=> false,
				'id'=>'3-3',
				'iconCls'=>'x-tree-icon-hide',
				'children'=>array(
					array(
						'text'=>'采购入库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Dahuo_CaigouRk&action=Right',
						'leaf'=>true,
						'id'=>'3-3-2',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'加工入库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Dahuo_JiagongRk&action=Add',
						'leaf'=>true,
						'id'=>'3-3-3',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'其他入库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Dahuo_QtRk&action=Add',
						'leaf'=>true,
						'id'=>'3-3-4',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'入库查询',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Dahuo_QtRk&action=Right',
						'leaf'=>true,
						'id'=>'3-3-5',
						'iconSpan'=>'x-tree-icon-hide',
					),
					// array(
					// 	'text'=>'销售出库单',
					// 	'expanded'=> false,
					// 	'src'=>'?controller=Cangku_Dahuo_Plan&action=Right',
					// 	'leaf'=>true,
					// 	'id'=>'3-3-6',
					// 	'iconSpan'=>'x-tree-icon-hide',
					// ),
					// array(
					// 	'text'=>'销售出库查询',
					// 	'expanded'=> false,
					// 	'src'=>'?controller=Cangku_Dahuo_Xsck&action=Right',
					// 	'leaf'=>true,
					// 	'id'=>'3-3-7',
					// 	'iconSpan'=>'x-tree-icon-hide',
					// ),
					array(
						'text'=>'外协出库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Dahuo_Jgck&action=Right',
						'leaf'=>true,
						'id'=>'3-3-8',
						'iconSpan'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'调货出库',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Dahuo_Diaohuo&action=Right',
						'leaf'=>true,
						'id'=>'3-3-9',
						'iconSpan'=>'x-tree-icon-hide',
					),/*
					array(
						'text'=>'调入确认',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Yangpin_Diaohuo&action=Rkshenhe',
						'leaf'=>true,
						'id'=>'3-3-10',
						'iconSpan'=>'x-tree-icon-hide',
					),*/
					array(
						'text'=>'大货库存报表',
						'expanded'=> false,
						'src'=>'?controller=Cangku_Dahuo_Report&action=ReportKucun',
						'leaf'=>true,
						'id'=>'3-3-12',
						'iconSpan'=>'x-tree-icon-hide',
					),
				)
			)				
		)
    ),
	array(
		'text'=>'财务管理',
		'expanded'=> false,
		'id'=>'4',
		'iconSpan'=>'glyphicon-usd',
		'children'=>array(
			array(
				'text'=>'应收款',
				'expanded'=> false,
				'id'=>'4-1',
				'iconCls'=>'x-tree-icon-hide',
				'children'=>array(
					array(
						'text'=>'销售发货过账',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_Guozhang&action=ListGuozhang',
						'leaf'=>true,
						'id'=>'4-1-1',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'销售发货过账查询',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_Guozhang&action=Right',
						'leaf'=>true,
						'id'=>'4-1-2',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'其他应收过账',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_GuozhangQt&action=Add',
						'leaf'=>true,
						'id'=>'4-1-3',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'其他应收过账查询',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_GuozhangQt&action=Right',
						'leaf'=>true,
						'id'=>'4-1-4',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'开票登记',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_Fapiao&action=Add',
						'leaf'=>true,
						'id'=>'4-1-5',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'按订单开票',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_Fapiao&action=ListOrder',
						'leaf'=>true,
						'id'=>'4-1-11',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'开票查询',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_Fapiao&action=Right',
						'leaf'=>true,
						'id'=>'4-1-6',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'其它收款',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_Income&action=Add',
						'leaf'=>true,
						'id'=>'4-1-7',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'收款查询',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_Income&action=Right',
						'leaf'=>true,
						'id'=>'4-1-8',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'应收款报表',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Ys_Guozhang&action=Report',
						'leaf'=>true,
						'id'=>'4-1-10',
						'iconCls'=>'x-tree-icon-hide',
					),
				)
			),
			array(
				'text'=>'应付款',
				'expanded'=> false,
				'id'=>'4-2',
				'iconCls'=>'x-tree-icon-hide',
				'children'=>array(
					array(
						'text'=>'采购过账',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_Guozhang&action=ListGuozhangCg',
						'leaf'=>true,
						'id'=>'4-2-1',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'加工过账',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_Guozhang&action=ListGuozhangJg',
						'leaf'=>true,
						'id'=>'4-2-2',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'应付款过账查询',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_Guozhang&action=Right',
						'leaf'=>true,
						'id'=>'4-2-3',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'其他应付过账',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_GuozhangQt&action=Add',
						'leaf'=>true,
						'id'=>'4-2-5',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'其他应付过账查询',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_GuozhangQt&action=Right',
						'leaf'=>true,
						'id'=>'4-2-6',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'收票登记',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_Fapiao&action=Add',
						'leaf'=>true,
						'id'=>'4-2-7',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'收票查询',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_Fapiao&action=Right',
						'leaf'=>true,
						'id'=>'4-2-8',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'付款登记',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_Fukuan&action=Add',
						'leaf'=>true,
						'id'=>'4-2-9',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'付款查询',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_Fukuan&action=Right',
						'leaf'=>true,
						'id'=>'4-2-10',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'应付款报表',
						'expanded'=> false,
						'src'=>'?controller=Caiwu_Yf_Guozhang&action=Report',
						'leaf'=>true,
						'id'=>'4-2-11',
						'iconCls'=>'x-tree-icon-hide',
					),
				)
			)		
		)
    ),
    array(
		'text'=>'报表中心',
		'expanded'=> false,
		'id'=>'14',
		'iconSpan'=>'glyphicon-list-alt',
		'children'=>array(
			array(
				'text'=>'申购单分类汇总',
				'expanded'=> false,
				'src'=>'?controller=Caigou_Shengou&action=Report',
				'leaf'=>true,
				'id'=>'14-1',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'供应商报价分析',
				'expanded'=> false,
				'src'=>'?controller=Caigou_Shengou&action=ReportSupplier',
				'leaf'=>true,
				'id'=>'14-2',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'花型销售统计报表',
				'expanded'=> false,
				'src'=>'?controller=Trade_Order&action=ReportViewOrder',
				'leaf'=>true,
				'id'=>'14-3',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'花型大类销售分析',
				'expanded'=> false,
				'src'=>'?controller=Chart_Order&action=ProcodeChart',
				'leaf'=>true,
				'id'=>'14-4',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'销售统计报表',
				'expanded'=> false,
				'src'=>'?controller=Trade_Order&action=ReportOrder',
				'leaf'=>true,
				'id'=>'14-5',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'现货/样品销售统计',
				'expanded'=> false,
				'src'=>'?controller=Trade_Order&action=ReportXhypOrder',
				'leaf'=>true,
				'id'=>'14-6',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'大货销售统计',
				'expanded'=> false,
				'src'=>'?controller=Trade_Order&action=ReportDhOrder',
				'leaf'=>true,
				'id'=>'14-8',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'采购合同进程分析报表',
				'expanded'=> false,
				'src'=>'?controller=Caigou_Order&action=ReportOrder',
				'leaf'=>true,
				'id'=>'14-7',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'销量查询分析报表',
				'expanded'=> false,
				'src'=>'?controller=Trade_Order&action=XiaoshouReport',
				'leaf'=>true,
				'id'=>'14-8',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'样品利润分析报表',
				'expanded'=> false,
				'src'=>'?controller=Trade_Order&action=YpLirunReport',
				'leaf'=>true,
				'id'=>'14-9',
				'iconCls'=>'x-tree-icon-hide',
			),
		)
    ),
	array(
		'text'=>'基础档案',
		'expanded'=> false,
		'id'=>'15',
		'iconSpan'=>'glyphicon-paperclip',
		'children'=>array(
			array(
				'text'=>'部门档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Department&action=Right',
				'leaf'=>true,
				'id'=>'15-1',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'员工档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Employ&action=Right',
				'leaf'=>true,
				'id'=>'15-2',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'理单员档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Lidan&action=Right',
				'leaf'=>true,
				'id'=>'15-12',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'客户档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Client&action=Right',
				'leaf'=>true,
				'id'=>'15-3',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'供应商档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Supplier&action=Right',
				'leaf'=>true,
				'id'=>'15-4',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'加工户档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Jiagonghu&action=Right',
				'leaf'=>true,
				'id'=>'15-10',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'库区档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Kuwei&action=Right',
				'leaf'=>true,
				'id'=>'15-5',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'库位档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_kuqu&action=Right',
				'leaf'=>true,
				'id'=>'15-11',
				'iconCls'=>'x-tree-icon-hide',
			),
			array(
				'text'=>'产品档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Product&action=Right',
				'leaf'=>true,
				'id'=>'15-9',
				'iconCls'=>'x-tree-icon-hide',
			),
			/*array(
				'text'=>'物料档案',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Wuliao&action=Right',
				'leaf'=>true,
				'id'=>'15-7',
				'iconCls'=>'x-tree-icon-hide',
			),*/
			array(
				'text'=>'银行账户',
				'expanded'=> false,
				'src'=>'?controller=Jichu_Bank&action=Right',
				'leaf'=>true,
				'id'=>'15-8',
				'iconCls'=>'x-tree-icon-hide',
			),
		)
    ),
	array(
		'text'=>'系统设置',
		'expanded'=> false,
		'id'=>'20',
		'iconSpan'=>'glyphicon-cog',
		'children'=>array(
			array(
				'text'=>'权限管理',
				'expanded'=> false,
				'id'=>'20-1',
				'icon'=>'Resource/Image/Menu/364.png',
				'iconSpan'=>'glyphicon-wrench',
				'children'=>array(
					array(
						'text'=>'用户管理',
						'iconCls'=>'x-tree-icon-hide',
						'expanded'=>false,
						'src'=>'?controller=Acm_User&action=right',
						'leaf'=>true,
						'id'=>'20-1-1'
					),
					array(
						'text'=>'组管理',
						'expanded'=> false,
						'src'=>'?controller=Acm_Role&action=right',
						'leaf'=>true,
						'id'=>'20-1-2',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'权限设置',
						'expanded'=> false,
						'src'=>'?controller=Acm_Func&action=setQx',
						'leaf'=>true,
						'id'=>'20-1-3',
						'iconCls'=>'x-tree-icon-hide',
					),
			)),
			array(
				'text'=>'审核设置',
				'expanded'=> false,
				'src'=>'?controller=Shenhe_Shenhe2Node&action=Edit',
				'leaf'=>true,
				'id'=>'20-3',
				'iconSpan'=>'glyphicon-link',
			),
			array(
				'text'=>'api日志',
				'expanded'=> false,				
				'id'=>'20-4',
				'icon'=>'Resource/Image/Menu/364.png',
				'iconSpan'=>'glyphicon-tower',
				'children'=>array(
					array(
						'text'=>'响应日志',
						'expanded'=> false,
						'src'=>'?controller=Api_Log&action=Right',
						'leaf'=>true,
						'id'=>'20-4-1',
						'iconCls'=>'x-tree-icon-hide',
					),
					array(
						'text'=>'调用日志',
						'expanded'=> false,
						'src'=>'?controller=Api_Log&action=callRight',
						'leaf'=>true,
						'id'=>'20-4-2',
						'iconCls'=>'x-tree-icon-hide',
					),
				),
			),
			array(
				'text'=>'计划任务日志',
				'expanded'=> false,
				'src'=>'?controller=CrontabLog&action=Right',
				'leaf'=>true,
				'id'=>'20-10',
				'iconSpan'=>'glyphicon-time',
			),
		)
	)
);
?>
